const tableData = [
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "mymusic.mp3",
    fileType: "multimedia",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
  {
    name: "myimage.jpg",
    fileType: "image",
    cid: "QmZWsxv4tEsCEzdE6ywgZide3Z3TrCEUGSShSotoFr8g2w",
    size: "300kb",
    lastModified: "Jan 23,2022",
  },
];

export default tableData;
